# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os
from os.path import join
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
PATH = '../2_Data'

In [3]:
PATH

'../2_Data'

In [4]:
#import global-data-on-sustainable-energy dataframe
df_global_data = pd.read_csv(join(PATH,'2_1_Original_Data','global-data-on-sustainable-energy.csv'))
df_global_data.head(10)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,0.59,...,252.06912,1.41,1549.999952,NaN,11.229715,242.031313,60,652230.0,33.93911,67.709953
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,0.64,...,304.42090,1.50,1759.999990,NaN,5.357403,263.733602,60,652230.0,33.93911,67.709953
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,0.75,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60,652230.0,33.93911,67.709953
8,Afghanistan,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,0.54,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60,652230.0,33.93911,67.709953
9,Afghanistan,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,0.78,...,975.04816,2.25,4880.000114,NaN,21.390528,437.268740,60,652230.0,33.93911,67.709953

In [5]:
# names of the columns of dataset details
df_global_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB

In [6]:
df_global_data.shape

(3649, 21)

In [7]:
#descriptive analysis
df_global_data.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
count,3649.000000,3639.000000,3480.000000,2718.000000,1.560000e+03,3455.000000,3628.000000,3523.000000,3628.000000,3607.000000,3649.000000,3442.000000,3.221000e+03,1512.000000,3332.000000,3367.000000,3.648000e+03,3648.000000,3648.000000
mean,2010.038367,78.933702,63.255287,113.137498,9.422400e+07,32.638165,70.365003,13.450190,23.968010,36.801182,25743.981745,5.307345,1.598665e+05,11.986707,3.441610,13283.774348,6.332135e+05,18.246388,14.822695
std,6.054228,30.275541,39.043658,244.167256,2.981544e+08,29.894901,348.051866,73.006623,104.431085,34.314884,34773.221366,3.532020,7.736611e+05,14.994644,5.686720,19709.866716,1.585519e+06,24.159232,66.348148
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,59.800890,23.175000,3.540000,2.600000e+05,6.515000,0.290000,0.000000,0.040000,2.877847,3116.737300,3.170000,2.020000e+03,2.137095,1.383302,1337.813437,2.571300e+04,3.202778,-11.779889
50%,2010.000000,98.361570,83.150000,32.910000,5.665000e+06,23.300000,2.970000,0.000000,1.470000,27.865068,13120.570000,4.300000,1.050000e+04,6.290766,3.559855,4578.633208,1.176000e+05,17.189877,19.145136
75%,2015.000000,100.000000,100.000000,112.210000,5.534750e+07,55.245000,26.837500,0.000000,9.600000,64.403792,33892.780000,6.027500,6.058000e+04,16.841638,5.830099,15768.615365,5.131200e+05,38.969719,46.199616
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

In [8]:
#data type of the dataframe
df_global_data.dtypes

Entity                                                               object
Year                                                                  int64
Access to electricity (% of population)                             float64
Access to clean fuels for cooking                                   float64
Renewable-electricity-generating-capacity-per-capita                float64
Financial flows to developing countries (US $)                      float64
Renewable energy share in the total final energy consumption (%)    float64
Electricity from fossil fuels (TWh)                                 float64
Electricity from nuclear (TWh)                                      float64
Electricity from renewables (TWh)                                   float64
Low-carbon electricity (% electricity)                              float64
Primary energy consumption per capita (kWh/person)                  float64
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         float64
Value_co2_emissions_kt_by_country                                   float64
Renewables (% equivalent primary energy)                            float64
gdp_growth                                                          float64
gdp_per_capita                                                      float64
Density\n(P/Km2)                                                     object
Land Area(Km2)                                                      float64
Latitude                                                            float64
Longitude                                                           float64
dtype: object

In [9]:
#check for missing values
df_global_data.isnull().sum()

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                               10
Access to clean fuels for cooking                                    169
Renewable-electricity-generating-capacity-per-capita                 931
Financial flows to developing countries (US $)                      2089
Renewable energy share in the total final energy consumption (%)     194
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          207
Value_co2_emissions_kt_by_country                                    428
Renewables (% equivalent primary energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
Density\n(P/Km2)                                                       1
Land Area(Km2)                                                         1
Latitude                                                               1
Longitude                                                              1
dtype: int64

In [10]:
#Rename columns for readability
df_global_data.rename(columns = {'Entity' : 'Country'}, inplace = True)
df_global_data.head()

,Country,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

# import World Development Indicators dataframe

In [11]:
df_WDI_Country = pd.read_csv(join(PATH,'2_1_Original_Data','WDI_Country.csv'))
df_WDI_Country.head(10)

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,NaN
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,"26 countries, stretching from the Red Sea in t...",NaN,NaN,ZH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,The reporting period for national accounts dat...,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,"22 countries, stretching from the westernmost ...",NaN,NaN,ZI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,The World Bank systematically assesses the app...,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,NaN
5,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,NaN
6,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income,AD,...,NaN,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2018.0,NaN
7,ARB,Arab World,Arab World,Arab World,1A,NaN,Arab World aggregate. Arab World is composed o...,NaN,NaN,1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,NaN,Middle East & North Africa,High income,AE,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),"World Health Survey, 2003",NaN,Yes,2012,1985.0,2018.0,NaN
9,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,The World Bank systematically assesses the app...,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2020 (expected),"Multiple Indicator Cluster Survey, 2019/20","Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,NaN

In [12]:
df_WDI_Country.shape

(265, 31)

In [17]:
# names of the columns of dataset details
df_WDI_Country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country_Code                                       265 non-null    object
 1   Short_Name                                         265 non-null    object
 2   Country                                            265 non-null    object
 3   Long_Name                                          265 non-null    object
 4   2-alpha code                                       263 non-null    object
 5   Currency Unit                                      217 non-null    object
 6   Special Notes                                      126 non-null    object
 7   Region                                             217 non-null    object
 8   Income Group                                       216 non-null    object
 9   WB-2 code                                          264 non-null    object
 10  National accounts base year                        209 non-null    object
 11  National accounts reference year                   74 non-null     float64
 12  SNA price valuation                                207 non-null    object
 13  Lending category                                   144 non-null    object
 14  Other groups                                       59 non-null     object
 15  System of National Accounts                        208 non-null    object
 16  Alternative conversion factor                      0 non-null      float64
 17  PPP survey year                                    0 non-null      float64
 18  Balance of Payments Manual in use                  194 non-null    object
 19  External debt Reporting status                     122 non-null    object
 20  System of trade                                    172 non-null    object
 21  Government Accounting concept                      158 non-null    object
 22  IMF data dissemination standard                    188 non-null    object
 23  Latest population census                           214 non-null    object
 24  Latest household survey                            154 non-null    object
 25  Source of most recent Income and expenditure data  168 non-null    object
 26  Vital registration complete                        120 non-null    object
 27  Latest agricultural census                         128 non-null    object
 28  Latest industrial data                             147 non-null    float64
 29  Latest trade data                                  191 non-null    float64
 30  Latest water withdrawal data                       0 non-null      float64
dtypes: float64(6), object(25)
memory usage: 64.3+ KB

In [18]:
#descriptive analysis
df_WDI_Country.describe()

,National accounts reference year,Alternative conversion factor,PPP survey year,Latest industrial data,Latest trade data,Latest water withdrawal data
count,74.000000,0.0,0.0,147.000000,191.000000,0.0
mean,2013.445946,NaN,NaN,2007.040816,2016.633508,NaN
std,4.217192,NaN,NaN,9.420815,3.256043,NaN
min,2000.000000,NaN,NaN,1973.000000,1995.000000,NaN
25%,2012.000000,NaN,NaN,2002.500000,2017.000000,NaN
50%,2015.000000,NaN,NaN,2012.000000,2018.000000,NaN
75%,2015.000000,NaN,NaN,2013.000000,2018.000000,NaN
max,2022.000000,NaN,NaN,2014.000000,2018.000000,NaN

In [19]:
#data type of the dataframe
df_WDI_Country.dtypes

Country_Code                                          object
Short_Name                                            object
Country                                               object
Long_Name                                             object
2-alpha code                                          object
Currency Unit                                         object
Special Notes                                         object
Region                                                object
Income Group                                          object
WB-2 code                                             object
National accounts base year                           object
National accounts reference year                     float64
SNA price valuation                                   object
Lending category                                      object
Other groups                                          object
System of National Accounts                           object
Alternative conversion factor                        float64
PPP survey year                                      float64
Balance of Payments Manual in use                     object
External debt Reporting status                        object
System of trade                                       object
Government Accounting concept                         object
IMF data dissemination standard                       object
Latest population census                              object
Latest household survey                               object
Source of most recent Income and expenditure data     object
Vital registration complete                           object
Latest agricultural census                            object
Latest industrial data                               float64
Latest trade data                                    float64
Latest water withdrawal data                         float64
dtype: object

In [20]:
#check for missing values
df_WDI_Country.isnull().sum()

Country_Code                                           0
Short_Name                                             0
Country                                                0
Long_Name                                              0
2-alpha code                                           2
Currency Unit                                         48
Special Notes                                        139
Region                                                48
Income Group                                          49
WB-2 code                                              1
National accounts base year                           56
National accounts reference year                     191
SNA price valuation                                   58
Lending category                                     121
Other groups                                         206
System of National Accounts                           57
Alternative conversion factor                        265
PPP survey year                                      265
Balance of Payments Manual in use                     71
External debt Reporting status                       143
System of trade                                       93
Government Accounting concept                        107
IMF data dissemination standard                       77
Latest population census                              51
Latest household survey                              111
Source of most recent Income and expenditure data     97
Vital registration complete                          145
Latest agricultural census                           137
Latest industrial data                               118
Latest trade data                                     74
Latest water withdrawal data                         265
dtype: int64

In [13]:
# renmae "Table_Name" column,to read Country

df_WDI_Country.rename(columns = {'Table_Name' : 'Country'}, inplace = True)

In [21]:
df_WDI_Country.rename(columns = {'Short_Name' : 'Country_Short_Name'}, inplace = True)
df_WDI_Country.rename(columns = {'Long_Name' : 'Country_Long_Name'}, inplace = True)

In [28]:
# Drop unnecessary/empty columns 
df_WDI_Country = df_WDI_Country.drop(['Alternative conversion factor'], axis=1)
df_WDI_Country = df_WDI_Country.drop(['PPP survey year'], axis=1)
df_WDI_Country = df_WDI_Country.drop(['Latest water withdrawal data'], axis=1)

In [29]:
df_WDI_Country.head()

,Country_Code,Country_Short_Name,Country,Country_Long_Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,"26 countries, stretching from the Red Sea in t...",NaN,NaN,ZH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,The reporting period for national accounts dat...,South Asia,Low income,AF,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,"22 countries, stretching from the westernmost ...",NaN,NaN,ZI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,The World Bank systematically assesses the app...,Sub-Saharan Africa,Lower middle income,AO,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0

# merge global-data-on-sustainable-energy dataframe with World Development Indicators dataframe

In [24]:
df_combined_global_details = pd.merge(df_global_data, df_WDI_Country, how='left', on='Country')
df_combined_global_details.head()

,Country,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0

In [25]:
df_combined_global_details.shape

(3649, 48)

In [26]:
# Export 'ords_prods_group' dataframe to prepared data folder in pickle format
df_combined_global_details.to_csv(join(PATH,'2_2_Prepared_Data','df_combined_global_details.csv'))